# Hand-run LLM binder output (plan step 8), performed by direct reasoning
# instead of an `anthropic` API call (no ANTHROPIC_API_KEY in this
# environment -- see report/FINDINGS.md for the methodology note on why
# this makes Phase 2 a worked demonstration rather than a blind eval).
#
# For each of the 39 gold candidates, two independent binding judgments:
#  - NAME_ONLY: given only "Node path" + "Node name" + lexicon (id,
#    preferred_name, synonyms) -- no description, no lexicon definitions.
#  - DEFINITION_BASED: given "Node path" + full description + lexicon (id,
#    preferred_name, definition) -- no synonyms shown.
# Each entry: (corpus, module, path, lexicon_id, relation, confidence)
# in the same row order as data/gold/gold_standard.csv.

NAME_ONLY = [
    ("ietf", "ietf-network", "/networks/network/node", "LEX-001", "equivalent", 0.95),
    ("ietf", "ietf-network-topology", "/networks/network/node/termination-point", "LEX-002", "equivalent", 0.95),
    ("ietf", "ietf-network-topology", "/networks/network/link", "LEX-004", "equivalent", 0.95),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/tunnel-termination-point", "LEX-003", "equivalent", 0.85),
    ("ietf", "ietf-network-topology", "/networks/network/node/termination-point/supporting-termination-point",
     "LEX-002", "equivalent", 0.8),
    ("ietf", "ietf-otn-topology", "/networks/network/node/termination-point/te/client-svc", "LEX-007", "equivalent", 0.9),
    ("ietf", "ietf-te-topology",
     "/networks/network/node/te/te-node-attributes/connectivity-matrices/underlay/tunnels/tunnel",
     "LEX-006", "equivalent", 0.85),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/te-node-attributes/connectivity-matrices/path-constraints",
     "LEX-008", "equivalent", 0.8),
    ("ietf", "ietf-te-topology", "/networks/network/te/nsrlg", "LEX-009", "equivalent", 0.9),
    ("ietf", "ietf-otn-topology",
     "/networks/network/node/termination-point/te/interface-switching-capability/max-lsp-bandwidth/te-bandwidth/technology/otn-bandwidth/odu-type",
     "LEX-010", "equivalent", 0.9),
    ("ietf", "ietf-te-topology", "/networks/network/node/termination-point/te/admin-status", "LEX-011", "equivalent", 0.9),
    ("ietf", "ietf-te-topology", "/networks/network/node/termination-point/te/oper-status", "LEX-012", "equivalent", 0.9),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/te-link-attributes", "LEX-004", "equivalent", 0.6),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/te-node-attributes", "LEX-001", "equivalent", 0.6),
    ("ietf", "ietf-otn-topology", "/networks/network/link/te/te-link-attributes/otn-link", "LEX-004", "equivalent", 0.6),
    ("ietf", "ietf-otn-topology", "/networks/network/node/te/te-node-attributes/otn-node", "LEX-001", "equivalent", 0.6),
    ("ietf", "ietf-network-topology", "/networks/network/link/supporting-link", "LEX-004", "equivalent", 0.85),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/bundle-stack-level/bundled-links/bundled-link",
     "LEX-004", "subsumed_by", 0.8),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/bundle-stack-level/component-links/component-link",
     "LEX-004", "subsumed_by", 0.8),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/te-node-template", "LEX-001", "subsumed_by", 0.5),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/te-link-template", "LEX-004", "subsumed_by", 0.5),
    ("ietf", "ietf-te-topology",
     "/networks/network/node/te/te-node-attributes/connectivity-matrices/path-constraints/path-srlgs-lists/path-srlgs-list",
     "LEX-009", "subsumes", 0.9),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node", "LEX-001", "equivalent", 0.95),
    # TRAP: name-only has no synonym overlap with LEX-002; "node" substring pulls toward LEX-001 instead
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point",
     "LEX-001", "equivalent", 0.55),
    ("tapi", "tapi-topology", "/context/topology-context/topology/link", "LEX-004", "equivalent", 0.95),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service", "LEX-006", "equivalent", 0.9),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/end-point", "LEX-007", "equivalent", 0.6),
    ("tapi", "tapi-connectivity", "/context/topology-context/topology/node/owned-node-edge-point/cep-list/connection-end-point",
     "LEX-007", "equivalent", 0.9),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/connectivity-constraint",
     "LEX-008", "equivalent", 0.7),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/routing-constraint",
     "LEX-008", "subsumed_by", 0.9),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/topology-constraint",
     "LEX-008", "subsumed_by", 0.9),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/node-rule-group/risk-characteristic",
     "LEX-009", "equivalent", 0.9),
    ("tapi", "tapi-topology", "/context/topology-context/topology/link/layer-protocol-name", "LEX-005", "subsumed_by", 0.9),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point/layer-protocol-name",
     "LEX-005", "subsumed_by", 0.9),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point/operational-state",
     "LEX-012", "equivalent", 0.95),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point/lifecycle-state",
     "LEX-011", "equivalent", 0.9),
    # TRAP/gap: no exact synonym for "service-interface-point"; "service" token pulls toward LEX-006 instead
    ("tapi", "tapi-common", "/context/service-interface-point", "LEX-006", "equivalent", 0.5),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/node-rule-group", "NONE", "none", 0.5),
    ("tapi", "tapi-path-computation", "/context/path-computation-context/path/link", "LEX-004", "equivalent", 0.9),
]

DEFINITION_BASED = [
    ("ietf", "ietf-network", "/networks/network/node", "LEX-001", "equivalent", 0.9),
    ("ietf", "ietf-network-topology", "/networks/network/node/termination-point", "LEX-002", "equivalent", 0.95),
    ("ietf", "ietf-network-topology", "/networks/network/link", "LEX-004", "equivalent", 0.95),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/tunnel-termination-point", "LEX-003", "equivalent", 0.9),
    ("ietf", "ietf-network-topology", "/networks/network/node/termination-point/supporting-termination-point",
     "LEX-002", "equivalent", 0.85),
    ("ietf", "ietf-otn-topology", "/networks/network/node/termination-point/te/client-svc", "LEX-007", "equivalent", 0.6),
    ("ietf", "ietf-te-topology",
     "/networks/network/node/te/te-node-attributes/connectivity-matrices/underlay/tunnels/tunnel",
     "LEX-006", "equivalent", 0.75),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/te-node-attributes/connectivity-matrices/path-constraints",
     "LEX-008", "equivalent", 0.75),
    ("ietf", "ietf-te-topology", "/networks/network/te/nsrlg", "LEX-009", "equivalent", 0.55),
    ("ietf", "ietf-otn-topology",
     "/networks/network/node/termination-point/te/interface-switching-capability/max-lsp-bandwidth/te-bandwidth/technology/otn-bandwidth/odu-type",
     "LEX-010", "equivalent", 0.7),
    ("ietf", "ietf-te-topology", "/networks/network/node/termination-point/te/admin-status", "LEX-011", "equivalent", 0.9),
    ("ietf", "ietf-te-topology", "/networks/network/node/termination-point/te/oper-status", "LEX-012", "equivalent", 0.9),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/te-link-attributes", "LEX-004", "subsumed_by", 0.6),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/te-node-attributes", "LEX-001", "subsumed_by", 0.6),
    ("ietf", "ietf-otn-topology", "/networks/network/link/te/te-link-attributes/otn-link", "LEX-004", "subsumed_by", 0.6),
    ("ietf", "ietf-otn-topology", "/networks/network/node/te/te-node-attributes/otn-node", "LEX-001", "subsumed_by", 0.6),
    ("ietf", "ietf-network-topology", "/networks/network/link/supporting-link", "LEX-004", "equivalent", 0.75),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/bundle-stack-level/bundled-links/bundled-link",
     "LEX-004", "subsumed_by", 0.55),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/bundle-stack-level/component-links/component-link",
     "LEX-004", "subsumed_by", 0.5),
    ("ietf", "ietf-te-topology", "/networks/network/node/te/te-node-template", "LEX-001", "subsumed_by", 0.55),
    ("ietf", "ietf-te-topology", "/networks/network/link/te/te-link-template", "LEX-004", "subsumed_by", 0.55),
    ("ietf", "ietf-te-topology",
     "/networks/network/node/te/te-node-attributes/connectivity-matrices/path-constraints/path-srlgs-lists/path-srlgs-list",
     "LEX-009", "subsumes", 0.85),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node", "LEX-001", "equivalent", 0.9),
    # trap resolved: description explains NEPs are boundary points OWNED BY the node, matching LEX-002's
    # genus ("a boundary point on a forwarding element") rather than LEX-001 ("the forwarding element itself")
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point",
     "LEX-002", "equivalent", 0.7),
    ("tapi", "tapi-topology", "/context/topology-context/topology/link", "LEX-004", "equivalent", 0.9),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service", "LEX-006", "equivalent", 0.8),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/end-point", "LEX-007", "equivalent", 0.75),
    ("tapi", "tapi-connectivity", "/context/topology-context/topology/node/owned-node-edge-point/cep-list/connection-end-point",
     "LEX-007", "equivalent", 0.75),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/connectivity-constraint",
     "LEX-008", "equivalent", 0.6),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/routing-constraint",
     "LEX-008", "subsumed_by", 0.6),
    ("tapi", "tapi-connectivity", "/context/connectivity-context/connectivity-service/topology-constraint",
     "LEX-008", "subsumed_by", 0.65),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/node-rule-group/risk-characteristic",
     "LEX-009", "equivalent", 0.9),
    ("tapi", "tapi-topology", "/context/topology-context/topology/link/layer-protocol-name", "LEX-005", "subsumed_by", 0.7),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point/layer-protocol-name",
     "LEX-005", "subsumed_by", 0.7),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point/operational-state",
     "LEX-012", "equivalent", 0.9),
    # subtle case: surface name doesn't suggest "administrative", but the description's "planned
    # deployment/allocation/withdrawal" (operator intent) vs LEX-012's "real capability...right now"
    # (observed behavior) is exactly the LEX-011/LEX-012 differentia
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/owned-node-edge-point/lifecycle-state",
     "LEX-011", "equivalent", 0.65),
    ("tapi", "tapi-common", "/context/service-interface-point", "LEX-007", "equivalent", 0.55),
    ("tapi", "tapi-topology", "/context/topology-context/topology/node/node-rule-group", "NONE", "none", 0.7),
    ("tapi", "tapi-path-computation", "/context/path-computation-context/path/link", "LEX-004", "equivalent", 0.85),
]

assert len(NAME_ONLY) == 39, len(NAME_ONLY)
assert len(DEFINITION_BASED) == 39, len(DEFINITION_BASED)
